version: '3'

services:
  restApi:
    container_name: restApi
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
    image: api-test
    working_dir: /var/www/restApi.loc/html
    volumes:
      - ./:/var/www/restApi.loc/html:rw
    depends_on:
      - postrgesql
      - postrgesql_test
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    networks:
      - restApi

  nginx:
    container_name: restApi-nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www/restApi.loc/html:rw
    ports:
      - "80:80"
    links:
      - restApi
    networks:
      - restApi

  postrgesql:
    container_name: restApi-postrgesql
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: restApi
    networks:
      - restApi

  postrgesql_test:
    container_name: test-restApi-postrgesql
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: test-restApi
    networks:
      - restApi

networks:
  restApi:
    driver: bridge
